In [116]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

In [172]:
from luxai_s3.wrappers import LuxAIS3GymEnv

env = LuxAIS3GymEnv(numpy_output=True)

obs, info = env.reset(seed=42)

In [173]:
info['full_params']

{'max_steps_in_match': 100,
 'map_type': 1,
 'map_width': 24,
 'map_height': 24,
 'num_teams': 2,
 'match_count_per_episode': 5,
 'max_units': 16,
 'init_unit_energy': 100,
 'min_unit_energy': 0,
 'max_unit_energy': 400,
 'unit_move_cost': 2,
 'spawn_rate': 3,
 'unit_sap_cost': 49,
 'unit_sap_range': 6,
 'unit_sap_dropoff_factor': 1.0,
 'unit_energy_void_factor': 0.25,
 'max_energy_nodes': 6,
 'max_energy_per_tile': 20,
 'min_energy_per_tile': -20,
 'max_relic_nodes': 6,
 'relic_config_size': 5,
 'fog_of_war': True,
 'unit_sensor_range': 2,
 'nebula_tile_vision_reduction': 1,
 'nebula_tile_energy_reduction': 10,
 'nebula_tile_drift_speed': -0.02500000037252903,
 'energy_node_drift_speed': 0.05000000074505806,
 'energy_node_drift_magnitude': 4}

# random runs for some steps

In [159]:
a = env.action_space.sample()

a['player_0']

array([[ 4, -2,  3],
       [ 5,  3, -3],
       [ 6,  2,  4],
       [ 4, -1,  0],
       [ 0,  1,  4],
       [ 3, -2, -1],
       [ 4,  1,  1],
       [ 2, -2, -4],
       [ 3,  4, -1],
       [ 3, -4,  0],
       [ 5,  4,  4],
       [ 2, -4,  1],
       [ 3, -2,  1],
       [ 6, -3,  3],
       [ 6,  2,  4],
       [ 4,  1,  0]], dtype=int16)

In [160]:
for i in range(80):
    obs, reward, terminated, truncated, info = env.step(env.action_space.sample())

In [161]:
obs.keys()

dict_keys(['player_0', 'player_1'])

In [162]:
player = obs['player_0']

dir(player)

['__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__ior__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__ror__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'clear',
 'copy',
 'fromkeys',
 'get',
 'items',
 'keys',
 'pop',
 'popitem',
 'setdefault',
 'update',
 'values']

# Steps and Match

In [163]:
obs['player_0'].keys()

dict_keys(['units', 'units_mask', 'sensor_mask', 'map_features', 'relic_nodes', 'relic_nodes_mask', 'team_points', 'team_wins', 'steps', 'match_steps'])

In [164]:
player_0 = obs['player_0']

In [165]:
player_0['steps']

array(80, dtype=int32)

In [166]:
player_0['match_steps']

array(80, dtype=int32)

In [167]:
player_0['team_wins']

array([0, 0], dtype=int32)

In [177]:
for i in range(30):
    obs, reward, terminated, truncated, info = env.step(env.action_space.sample())
    player_0 = obs['player_0']
    print(terminated, player_0['steps'], player_0['match_steps'], player_0['team_wins'])

{'player_0': array(False), 'player_1': array(False)} 91 91 [0 0]
{'player_0': array(False), 'player_1': array(False)} 92 92 [0 0]
{'player_0': array(False), 'player_1': array(False)} 93 93 [0 0]
{'player_0': array(False), 'player_1': array(False)} 94 94 [0 0]
{'player_0': array(False), 'player_1': array(False)} 95 95 [0 0]
{'player_0': array(False), 'player_1': array(False)} 96 96 [0 0]
{'player_0': array(False), 'player_1': array(False)} 97 97 [0 0]
{'player_0': array(False), 'player_1': array(False)} 98 98 [0 0]
{'player_0': array(False), 'player_1': array(False)} 99 99 [0 0]
{'player_0': array(False), 'player_1': array(False)} 100 100 [0 0]
{'player_0': array(False), 'player_1': array(False)} 101 0 [0 1]
{'player_0': array(False), 'player_1': array(False)} 102 1 [0 1]
{'player_0': array(False), 'player_1': array(False)} 103 2 [0 1]
{'player_0': array(False), 'player_1': array(False)} 104 3 [0 1]
{'player_0': array(False), 'player_1': array(False)} 105 4 [0 1]
{'player_0': array(Fals

In [181]:
player_0['team_wins'] - obs['player_1']['team_wins']

array([0, 0], dtype=int32)

In [154]:
if player_0['steps'] >= 504:
    print('yes', player_0['steps'])
else:
    print('no')

yes 510


# Info

In [128]:
info.keys()

dict_keys(['discount', 'final_observation', 'final_state', 'player_0', 'player_1'])

EnvObs(units=UnitState(position=Array([[[ 0,  4],
        [ 1,  3],
        [ 5,  5],
        [ 3,  2],
        [ 0,  5],
        [ 2,  1],
        [ 2,  2],
        [ 2,  5],
        [ 1,  2],
        [ 0,  4],
        [ 0,  1],
        [ 1,  5],
        [ 1,  3],
        [ 0,  5],
        [ 0,  1],
        [ 0,  3]],

       [[-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1],
        [-1, -1]]], dtype=int16), energy=Array([[  0,   0,  82,  40,   0,   0,   0, 105, 176,   4, 336,  26,   0,
         43, 327, 228],
       [ -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,
         -1,  -1,  -1]], dtype=int16)), units_mask=Array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True],
       [False, Fa